# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 23))
        self.menubar.setObjectName("menubar")
        self.menu_project = QtWidgets.QMenu(self.menubar)
        self.menu_project.setObjectName("menu_project")
        self.menu_operation = QtWidgets.QMenu(self.menubar)
        self.menu_operation.setObjectName("menu_operation")
        self.menu_window = QtWidgets.QMenu(self.menubar)
        self.menu_window.setObjectName("menu_window")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_project_file = QtWidgets.QAction(MainWindow)
        self.open_project_file.setObjectName("open_project_file")
        self.save_project_file = QtWidgets.QAction(MainWindow)
        self.save_project_file.setObjectName("save_project_file")
        self.save_as = QtWidgets.QAction(MainWindow)
        self.save_as.setObjectName("save_as")
        self.add_board = QtWidgets.QAction(MainWindow)
        self.add_board.setObjectName("add_board")
        self.to_load_system = QtWidgets.QAction(MainWindow)
        self.to_load_system.setObjectName("to_load_system")
        self.restoration_system = QtWidgets.QAction(MainWindow)
        self.restoration_system.setObjectName("restoration_system")
        self.refresh_all = QtWidgets.QAction(MainWindow)
        self.refresh_all.setObjectName("refresh_all")
        self.refresh = QtWidgets.QAction(MainWindow)
        self.refresh.setObjectName("refresh")
        self.export_file = QtWidgets.QAction(MainWindow)
        self.export_file.setObjectName("export_file")
        self.in_file = QtWidgets.QAction(MainWindow)
        self.in_file.setObjectName("in_file")
        self.stack_up = QtWidgets.QAction(MainWindow)
        self.stack_up.setObjectName("stack_up")
        self.tile_horizontal = QtWidgets.QAction(MainWindow)
        self.tile_horizontal.setObjectName("tile_horizontal")
        self.Vertical_flat_out = QtWidgets.QAction(MainWindow)
        self.Vertical_flat_out.setObjectName("Vertical_flat_out")
        self.minimization = QtWidgets.QAction(MainWindow)
        self.minimization.setObjectName("minimization")
        self.arrangement = QtWidgets.QAction(MainWindow)
        self.arrangement.setObjectName("arrangement")
        self.Waveform_view = QtWidgets.QAction(MainWindow)
        self.Waveform_view.setObjectName("Waveform_view")
        self.Memory_view = QtWidgets.QAction(MainWindow)
        self.Memory_view.setObjectName("Memory_view")
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.menu_project.addAction(self.open_project_file)
        self.menu_project.addAction(self.save_project_file)
        self.menu_project.addAction(self.save_as)
        self.menu_project.addSeparator()
        self.menu_project.addAction(self.add_board)
        self.menu_operation.addAction(self.to_load_system)
        self.menu_operation.addAction(self.restoration_system)
        self.menu_operation.addAction(self.refresh_all)
        self.menu_operation.addAction(self.refresh)
        self.menu_operation.addAction(self.export_file)
        self.menu_operation.addAction(self.in_file)
        self.menu_window.addAction(self.stack_up)
        self.menu_window.addAction(self.tile_horizontal)
        self.menu_window.addAction(self.Vertical_flat_out)
        self.menu_window.addAction(self.minimization)
        self.menu_window.addAction(self.arrangement)
        self.menu_window.addSeparator()
        self.menu_window.addAction(self.Waveform_view)
        self.menu_window.addAction(self.Memory_view)
        self.menu_Help.addAction(self.help)
        self.menubar.addAction(self.menu_project.menuAction())
        self.menubar.addAction(self.menu_operation.menuAction())
        self.menubar.addAction(self.menu_window.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_project.setTitle(_translate("MainWindow", "工程(&P)"))
        self.menu_operation.setTitle(_translate("MainWindow", "操作(&C)"))
        self.menu_window.setTitle(_translate("MainWindow", "窗口(&W)"))
        self.menu_Help.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.open_project_file.setText(_translate("MainWindow", "打开工程文件(&W)"))
        self.open_project_file.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.save_project_file.setText(_translate("MainWindow", "保存工程文件(&S)"))
        self.save_project_file.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.save_as.setText(_translate("MainWindow", "另存为(&Y)..."))
        self.save_as.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.add_board.setText(_translate("MainWindow", "添加新板卡(&Z)."))
        self.add_board.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.to_load_system.setText(_translate("MainWindow", "加载全系统(&U)"))
        self.to_load_system.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.restoration_system.setText(_translate("MainWindow", "复位全系统(&V)"))
        self.restoration_system.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.refresh_all.setText(_translate("MainWindow", "刷新所有变量(&A)"))
        self.refresh_all.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.refresh.setText(_translate("MainWindow", "刷新(&X)"))
        self.refresh.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.export_file.setText(_translate("MainWindow", "导出文件(&D)"))
        self.export_file.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.in_file.setText(_translate("MainWindow", "导入文件(&T)"))
        self.in_file.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.stack_up.setText(_translate("MainWindow", "层叠(&S)"))
        self.stack_up.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.tile_horizontal.setText(_translate("MainWindow", "水平平铺(&T)"))
        self.tile_horizontal.setShortcut(_translate("MainWindow", "Ctrl+Shift+T"))
        self.Vertical_flat_out.setText(_translate("MainWindow", "垂直平铺(&V)"))
        self.Vertical_flat_out.setShortcut(_translate("MainWindow", "Ctrl+Shift+V"))
        self.minimization.setText(_translate("MainWindow", "全部最小化"))
        self.arrangement.setText(_translate("MainWindow", "排列"))
        self.Waveform_view.setText(_translate("MainWindow", "波形视图(&W)"))
        self.Waveform_view.setShortcut(_translate("MainWindow", "Ctrl+Shift+W"))
        self.Memory_view.setText(_translate("MainWindow", "内存视图(&M)"))
        self.Memory_view.setShortcut(_translate("MainWindow", "Ctrl+Shift+M"))
        self.help.setText(_translate("MainWindow", "关于(&H)"))
        self.help.setShortcut(_translate("MainWindow", "Ctrl+Shift+H"))


